SparesShop/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SparesShop.Data;
using SparesShop.Interfaces;
using SparesShop.Models;
using SparesShop.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SparesShop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProducts _list;
        private readonly DatabaseContext _context;
        private readonly ICategory _category;


        public ProductsController(IProducts list, ICategory category, DatabaseContext context)
        {
            _list = list;
            _category = category;
            _context = context;

        }
        [Route("Product/ProductList")]
        [Route("Product/ProductList/{brand}")]
        public ActionResult ProductList(string brand, int p = 1, int s = 10)
        {
            var products = _list.ProductList(brand).Skip((p - 1) * s).Take(s);
            var CurrCategory = brand;
            var item = new ProductListViewModel
            {
                Products = products,
                CurrCategory = CurrCategory
            };

            ViewBag.PageCount = _list.ProductList(brand).Count();
            ViewBag.CurrentPage = p;
            ViewBag.PageSize = s;
            return View(item);
        }
    }

}

SparesShop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using SparesShop.Interfaces;
using SparesShop.Models;
using SparesShop.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SparesShop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IProducts _product;
        private readonly ShopCart _ShopCart;
        public readonly IShopCart _shopCart;
        public ShopCartController(IProducts product, ShopCart ShopCart, IShopCart shopCart)
        {
            _product = product;
            _shopCart = shopCart;
            _ShopCart = ShopCart;
        }
        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _ShopCart.ShopCartItems = items;

            var item = new ShopCartViewModel
            {
                ShopCart = _ShopCart
            };
            return View(item);
        }
        public RedirectToActionResult AddToCart(int id)
        {
            var item = _product.GetProducts.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

SparesShop/Views/Shared/ProductsPage.cshtml
@model Product
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">


</head>
<body>
    <div class="col-lg-3">
        <div class="card" style="width: 18rem;">
            @if (string.IsNullOrEmpty(Model.TitleImagePath))
            {
                <img src="https://yeella.com/files/uploads/error_404.png" class="card-img-top" alt="...">
            }
            else
            {
                <img src="/images/@Model.TitleImagePath" class="card-img-top" alt="...">
            }
        <div class="card-body">
            <p class="card-title">@Model.Brand</p>
            <p class="card-title">@Model.ArticleNumber</p>
            <p class="card-text">@Model.Name</p>
            <p class="card-text">@Model.Price.ToString()</p>
            @Html.ActionLink("Buy", "addToCart", "ShopCart", new { id = Model.Id }, new { @class = "btn btn-outline-info" })
        </div>
        </div>
    </div>
</body>
</html>

SparesShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/header.css" />
    <link rel="stylesheet" href="~/css/search.css" />

    
    <title>@ViewData["Title"]</title>

</head>
<body>
    <header>
        <div class="container">
            <nav class="nav">
                <a href="/" class="logo">SparesShop</a>
                <ul class="nav-list">
                    <li>
                        <a href="/" class="nav-link">Home</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-route-area="" asp-controller="Products" asp-action="ProductList">Catalog</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-route-area="" asp-controller="Home" asp-action="Links">Links</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-route-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-route-area="" asp-controller="ShopCart" asp-action="Index">
                            <div class="cart-icon">
                                <i class="fas fa-shopping-bag"></i>
                            </div>
                        </a>
                    </li>
                    @if (User.Identity.IsAuthenticated && User.Identity.Name == "alvion2045@mail.ru")
                    {
                        <li>
                            <a class="nav-link" href="/admin">AdminPanel</a>
                        </li>

                    }
                    @if (User.Identity.IsAuthenticated && User.Identity.Name != "alvion2045@mail.ru")
                    {
                        <li>
                            <a class="nav-link" href="/user">UserPanel</a>
                        </li>

                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a class="nav-link" asp-controller="Account" asp-action="Login" hidden>Signin</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Signin</a>
                        </li>
                    }


                    <li>
                        <a class="nav-link" href="/admin" hidden>AdminPanel</a>
                    </li>
                    <li>
                        <a class="nav-link" href="/user" hidden>AdminPanel</a>
                    </li>



                </ul>

                <form method="post" asp-route-area="" asp-controller="Home" asp-action="Search">
                    <div class="search-box">
                        <input type="search" name="search" placeholder="Search...">
                        <input type="hidden" name="p" value="p" />
                        <input type="hidden" name="s" value="s" />
                        <div class="search-icon">
                            <i class="fas fa-search"></i>
                        </div>
                        <div class="cancel-icon">
                            <i class="fas fa-times"></i>
                        </div>
                    </div>

                </form>
            </nav>
        </div>
    </header>
    @*<section class="hero"></section>*@
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/images/Баннер6.jpg" alt="Первый слайд">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/images/Баннер12.jpg" alt="Второй слайд" />
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/images/Баннер17.jpg" alt="Третий слайд">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <section class="demo-content"></section>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/uppage.js"></script>
    <script>
        window.addEventListener('scroll', function () {
            let header = document.querySelector('header');
            let windowPosition = window.scrollY > 0;
            header.classList.toggle('scrolling-active', windowPosition);
        })
    </script>
    <script>
        const searchBox = document.querySelector(".search-box");
        const searchBtn = document.querySelector(".search-icon");
        const cancelBtn = document.querySelector(".cancel-icon");
        const searchInput = document.querySelector("input");
        const searchData = document.querySelector(".search-data");
        searchBtn.onclick = () => {
            searchBox.classList.add("active");
            searchBtn.classList.add("active");
            searchInput.classList.add("active");
            cancelBtn.classList.add("active");
            searchInput.focus();
            if (searchInput.value != "") {
                var values = searchInput.value;
                searchData.classList.remove("active");
                searchData.innerHTML = "You just typed " + "<span style='font-weight: 500;'>" + values + "</span>";
            } else {
                searchData.textContent = "";
            }
        }
        cancelBtn.onclick = () => {
            searchBox.classList.remove("active");
            searchBtn.classList.remove("active");
            searchInput.classList.remove("active");
            cancelBtn.classList.remove("active");
            searchData.classList.toggle("active");
            searchInput.value = "";
        }
    </script>
    <script src="https://kit.fontawesome.com/0b38c30994.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>